import type {TabSchema} from '../schema/types';

export const ingressSchema: TabSchema = {
    key: 'ingress',
    label: '访问配置',
    fields: [
        {
            name: 'enableIngress',
            label: '启用外部访问',
            component: 'Switch',
            initialValue: false,
            tooltip: '开启后将创建 Ingress 规则，允许外部流量访问服务',
            aiMeta: { role: 'field', param: 'enableIngress', desc: '是否启用 Ingress' },
        },
        {
            name: 'ingressClass',
            label: 'Ingress 类型',
            component: 'Select',
            initialValue: 'nginx',
            visible: { fieldName: 'enableIngress', value: true },
            options: [
                { label: 'Nginx', value: 'nginx' },
                { label: 'Traefik', value: 'traefik' },
                { label: 'ALB', value: 'alb' },
            ],
            aiMeta: { role: 'field', param: 'ingressClass', desc: 'Ingress 控制器类型' },
        },
        {
            name: 'host',
            label: '域名',
            component: 'Input',
            visible: { fieldName: 'enableIngress', value: true },
            required: true,
            placeholder: '如 my-app.example.com',
            validators: [{ name: 'hostFormat' }],
            aiMeta: { role: 'field', param: 'host', desc: 'Ingress 域名' },
        },
        {
            name: 'path',
            label: '路径前缀',
            component: 'Input',
            visible: { fieldName: 'enableIngress', value: true },
            initialValue: '/',
            placeholder: '如 /api',
            validators: [{ name: 'pathFormat' }],
            aiMeta: { role: 'field', param: 'path', desc: 'Ingress 路径前缀' },
        },
        {
            name: 'servicePort',
            label: '服务端口',
            component: 'InputNumber',
            visible: { fieldName: 'enableIngress', value: true },
            required: true,
            componentProps: { min: 1, max: 65535, style: { width: '100%' } },
            validators: [{ name: 'portRange' }],
            aiMeta: { role: 'field', param: 'servicePort', desc: '后端服务端口' },
        },
        {
            name: 'enableTls',
            label: '启用 TLS',
            component: 'Switch',
            initialValue: false,
            visible: { fieldName: 'enableIngress', value: true },
            tooltip: '开启 HTTPS，需要提供 TLS 证书 Secret 名称',
            aiMeta: { role: 'field', param: 'enableTls', desc: '是否启用 TLS' },
        },
        {
            name: 'tlsSecretName',
            label: 'TLS Secret 名称',
            component: 'Input',
            visible: { fieldName: 'enableTls', value: true },
            required: true,
            placeholder: '如 my-app-tls',
            validators: [{ name: 'dnsLabel' }],
            aiMeta: { role: 'field', param: 'tlsSecretName', desc: 'TLS 证书 Secret 名称' },
        },
        {
            name: 'serviceType',
            label: 'Service 类型',
            component: 'Select',
            initialValue: 'ClusterIP',
            options: [
                { label: 'ClusterIP（集群内访问）', value: 'ClusterIP' },
                { label: 'NodePort（节点端口）', value: 'NodePort' },
                { label: 'LoadBalancer（负载均衡）', value: 'LoadBalancer' },
            ],
            aiMeta: { role: 'field', param: 'serviceType', desc: 'Kubernetes Service 类型' },
        },
        {
            name: 'nodePort',
            label: 'NodePort 端口',
            component: 'InputNumber',
            visible: { fieldName: 'serviceType', value: 'NodePort' },
            componentProps: { min: 30000, max: 32767, style: { width: '100%' } },
            tooltip: 'NodePort 范围为 30000-32767',
            validators: [{ name: 'nodePortRange' }],
            aiMeta: { role: 'field', param: 'nodePort', desc: 'NodePort 端口号' },
        },
    ],
};
