/**
 * Clusters 页面 Mock 数据
 */
import {Cluster} from '@/types/cluster';

export const mockClusters: Cluster[] = [
    {
        id: '1',
        name: 'aws-us-east-1',
        provider: 'aws',
        region: 'US East (N. Virginia)',
        status: 'healthy',
        version: '1.28.5',
        nodes: 12,
        pods: { running: 156, total: 180 },
        cpu: { used: 65, total: 100 },
        memory: { used: 78, total: 100 },
        gpus: [
            { type: 'A100', used: 3, total: 4 },
            { type: 'H100', used: 0, total: 1 },
        ],
        shared: false,
        applications: 8,
    },
    {
        id: '2',
        name: 'aws-eu-west-1',
        provider: 'aws',
        region: 'EU (Ireland)',
        status: 'healthy',
        version: '1.28.5',
        nodes: 8,
        pods: { running: 98, total: 120 },
        cpu: { used: 52, total: 100 },
        memory: { used: 61, total: 100 },
        shared: false,
        applications: 5,
    },
    {
        id: '3',
        name: 'aws-us-west-2',
        provider: 'aws',
        region: 'US West (Oregon)',
        status: 'healthy',
        version: '1.27.8',
        nodes: 6,
        pods: { running: 72, total: 90 },
        cpu: { used: 45, total: 100 },
        memory: { used: 55, total: 100 },
        shared: true,
        applications: 4,
    },
    {
        id: '4',
        name: 'gcp-us-central1',
        provider: 'gcp',
        region: 'US Central (Iowa)',
        status: 'healthy',
        version: '1.28.3',
        nodes: 10,
        pods: { running: 134, total: 150 },
        cpu: { used: 71, total: 100 },
        memory: { used: 68, total: 100 },
        shared: false,
        applications: 6,
    },
    {
        id: '5',
        name: 'gcp-asia-east1',
        provider: 'gcp',
        region: 'Asia East (Taiwan)',
        status: 'warning',
        version: '1.28.3',
        nodes: 4,
        pods: { running: 45, total: 60 },
        cpu: { used: 82, total: 100 },
        memory: { used: 89, total: 100 },
        shared: false,
        applications: 3,
    },
    {
        id: '6',
        name: 'bce-bj-1',
        provider: 'baidu',
        region: 'China (Beijing)',
        status: 'healthy',
        version: '1.27.5',
        nodes: 8,
        pods: { running: 88, total: 100 },
        cpu: { used: 58, total: 100 },
        memory: { used: 62, total: 100 },
        shared: true,
        applications: 4,
    },
];

export const cloudProviders = [
    { value: 'aws', label: 'AWS' },
    { value: 'gcp', label: 'GCP' },
    { value: 'baidu', label: '百度云' },
];
