/**
 * Environments 页面 Mock 数据
 */
import {Environment} from '@/types/environment';

export const mockEnvironments: Environment[] = [
    {
        id: 'prod-main',
        name: 'prod-main',
        displayName: 'Production Main',
        type: 'prod',
        level: 'production',
        status: 'healthy',
        isFeatureEnv: false,
        clusters: ['cn-beijing-prod', 'cn-shanghai-prod'],
        applications: 12,
        owner: 'platform-team',
        protected: true,
        expiresAt: null,
        lastDeployment: '5 分钟前',
        createdAt: '2024-01-15',
    },
    {
        id: 'staging-main',
        name: 'staging-main',
        displayName: 'Staging Main',
        type: 'staging',
        level: 'production',
        status: 'healthy',
        isFeatureEnv: false,
        clusters: ['cn-beijing-staging'],
        applications: 12,
        owner: 'platform-team',
        protected: true,
        expiresAt: null,
        lastDeployment: '30 分钟前',
        createdAt: '2024-01-15',
    },
    {
        id: 'staging-release-v2',
        name: 'staging-release-v2',
        displayName: 'Staging Release v2.0',
        type: 'staging',
        level: 'production',
        status: 'warning',
        isFeatureEnv: true,
        baseEnv: 'staging-main',
        routingType: 'service-mesh',
        clusters: ['cn-beijing-staging'],
        applications: 3,
        owner: 'release-team',
        protected: false,
        expiresAt: '2025-02-15',
        lastDeployment: '2 小时前',
        createdAt: '2025-01-20',
    },
    {
        id: 'sandbox-demo',
        name: 'sandbox-demo',
        displayName: 'Demo Environment',
        type: 'sandbox',
        level: 'testing',
        status: 'healthy',
        isFeatureEnv: false,
        clusters: ['cn-beijing-dev'],
        applications: 8,
        owner: 'sales-team',
        protected: true,
        expiresAt: null,
        lastDeployment: '1 天前',
        createdAt: '2024-06-01',
    },
    {
        id: 'test-base',
        name: 'test-base',
        displayName: 'Test Base',
        type: 'testing',
        level: 'testing',
        status: 'healthy',
        isFeatureEnv: false,
        clusters: ['cn-beijing-dev'],
        applications: 10,
        owner: 'qa-team',
        protected: false,
        expiresAt: null,
        lastDeployment: '3 小时前',
        createdAt: '2024-03-10',
    },
    {
        id: 'dev-main',
        name: 'dev-main',
        displayName: 'Development Main',
        type: 'dev',
        level: 'testing',
        status: 'healthy',
        isFeatureEnv: false,
        clusters: ['cn-beijing-dev'],
        applications: 15,
        owner: 'dev-team',
        protected: false,
        expiresAt: null,
        lastDeployment: '10 分钟前',
        createdAt: '2024-01-01',
    },
];
